### ISSUE TITLE
Prover test failure

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-circuits#790] opened 2022-09-21 14:02 UTC
- zkevm-circuit commit hash >> acf2c0b967ee3c073ce9195ef165d966666cecfa
- zkevm-chain commit hash  >> 68982510b93fd34e06f5d2f444a3807b90668b40

Reproducible examples: https://github.com/pinkiebell/tmp

```
Using circuit parameters: BLOCK_GAS_LIMIT=63000 MAX_TXS=3 MAX_CALLDATA=10500 MAX_BYTECODE=14000 MIN_K=19 STATE_CIRCUIT_PAD_TO=524032
```

glance of circuit bug
```
cat PROVER_LOG.txt| grep name | sort --unique
                        name: "",
                    name: "Execution step",
                    name: "assign bytecode",
                    name: "assign keccak rounds",
                    name: "ecc chip aux",
                    name: "ecdsa chip verification",
                    name: "length and data rlc",
                    name: "rw table",
                    name: "signature address verify",
                    name: "squeeze",
                name: "hash rlc check",
                name: "intermediate data rlc",
                name: "update data rlc",
            name: "Keccak",
            name: "composition_a",
            name: "composition_b",
            name: "composition_c",
            name: "composition_d",
            name: "keccak",
            name: "mpt_update exists in mpt circuit for Account last access",
            name: "overflow_a",
```

**Comment by ChihChengLiang** [comment] 2022-09-21 14:03
@pinkiebell @AronisAt79 can you update the zkevm-chain commit hash and zkevm-circuit commit hash on the description?

**Comment by AronisAt79** [comment] 2022-09-21 14:11
> @pinkiebell @AronisAt79 can you update the zkevm-chain commit hash and zkevm-circuit commit hash on the description?

done inline

**Comment by pinkiebell** [comment] 2022-09-22 12:08
Another note, a proving an empty block also has resulted in a `ConstraintSystemFailure`, that was with the real prover

**Comment by ChihChengLiang** [comment] 2022-09-23 07:49
> Another note, a proving an empty block also has resulted in a ConstraintSystemFailure, that was with the real prover

@ed255 do we need endblock to prove an empty block?

**Comment by pinkiebell** [comment] 2022-09-23 09:21
This time I have some debug information:
```
error: lookup input does not exist in table
  (L0, L1) ∉ (F38, F39)

  Lookup 'composition_a' inputs:
    L0 = x0
    ^
    | Cell layout in region 'ecdsa chip verification':
    |   | Offset | F40|
    |   +--------+----+
    |   |   129  | x0 | <--{ Lookup 'composition_a' inputs queried here
    |
    | Assigned cell values:
    |   x0 = 0x4

    L1 = x1 * x0
    ^
    | Cell layout in region 'ecdsa chip verification':
    |   | Offset |thread 'autogen_aggregation_verifier' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
    ```

**Comment by han0110** [comment] 2022-09-23 10:07
Ah I just checked again and found that the table of `RangeChip` used in `TxCircuit` is not loaded in `SuperCircuit`, it's only loaded in test circuits (the `SignVerifyConfig::load_range`).

Could you try call `config.tx_circuit.sign_verify.load_table(&mut layouter)?` in `SuperCircuit::synthesize` to see if it resolves the problem? (might need to make `sign_verify` in `TxCircuitConfig` `pub` first)

But if so, it's weird that test of `SuperCircuit` is working..

**Comment by ed255** [comment] 2022-09-23 11:05
> But if so, it's weird that test of `SuperCircuit` is working..

I'm not sure if the `SuperCircuit` tests are passing, as we're not running them (we disabled them because they take so much memory and time).  We have this issue to address this https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/794

**Comment by AronisAt79** [comment] 2022-09-26 13:11
Thanks @pinkiebell ! I am on it

**Comment by AronisAt79** [comment] 2022-09-26 15:50
@pinkiebell @ed255 @han0110 

retested proof generation on 
https://github.com/privacy-scaling-explorations/zkevm-chain/commit/7138394739bbe9166422fb5f461a330217603046

...still fails.

**Comment by ChihChengLiang** [comment] 2022-09-26 15:50
If that doesn't fix it. The data_rlc disagreement between different circuits might be the next possible place to investigate #799.

**Comment by han0110** [comment] 2022-09-27 10:55
> retested proof generation on [privacy-scaling-explorations/zkevm-chain@7138394](https://github.com/privacy-scaling-explorations/zkevm-chain/commit/7138394739bbe9166422fb5f461a330217603046)
> 
> ...still fails.

@AronisAt79 Is there a mock prover error log for this? I found log like https://github.com/pinkiebell/tmp/blob/master/PROVER_LOG.txt.xz is very helpful for me to debug.

**Comment by AronisAt79** [comment] 2022-09-27 11:40
> > retested proof generation on [privacy-scaling-explorations/zkevm-chain@7138394](https://github.com/privacy-scaling-explorations/zkevm-chain/commit/7138394739bbe9166422fb5f461a330217603046)
> > ...still fails.
> 
> @AronisAt79 Is there a mock prover error log for this? I found log like https://github.com/pinkiebell/tmp/blob/master/PROVER_LOG.txt.xz is very helpful for me to debug.

@han0110  sure, here it is:
[3ce88515fbc2b312536592a6aff5b2139b2418828537c0d52f06ca05efdae0f6-json.log](https://github.com/privacy-scaling-explorations/zkevm-circuits/files/9655035/3ce88515fbc2b312536592a6aff5b2139b2418828537c0d52f06ca05efdae0f6-json.log)

**Comment by han0110** [comment] 2022-09-27 13:21
The failed constraints and lookups from [3ce88515fbc2b312536592a6aff5b2139b2418828537c0d52f06ca05efdae0f6-json.log](https://github.com/privacy-scaling-explorations/zkevm-circuits/files/9655035/3ce88515fbc2b312536592a6aff5b2139b2418828537c0d52f06ca05efdae0f6-json.log) are:

- `bytecode_circuit::Config`
    - `assign bytecode`
    - `keccak` (lookup)
- `KeccakBitConfig`
    - `assign keccak rounds`
    - `hash rlc check`
    - `intermediate data rlc`
    - `length and data rlc`
    - `squeeze`
    - `update data rlc`
- `SignVerifyConfig`
    - `keccak` (lookup)
- `StateCircuit`
    - `mpt_update exists in mpt circuit for Account last access` (lookup)

But I just picked the tx from https://github.com/pinkiebell/tmp/blob/master/block.json to run with `TxCircuit` and succeeded. 

So I start to look into `KeccakBitConfig` and found that we are calling this in `SuperCircuit`:

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/77c5b62ee6c29ec4a2ae811a18fc81a6a64a0c2e/zkevm-circuits/src/super_circuit.rs#L153

which calls:

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/77c5b62ee6c29ec4a2ae811a18fc81a6a64a0c2e/zkevm-circuits/src/keccak_circuit/keccak_bit.rs#L102-L104

and makes the keccak input and output rlc value different. I have submitted PR #806 to fix this, hope that it can remove some errors.

**Comment by AronisAt79** [comment] 2022-09-27 14:07
@han0110 the tx you refer to is not associated to the failed case represented in the latest mock prover log. I will share the tx traces later today.

**Comment by AronisAt79** [comment] 2022-09-27 19:26
@han0110 attaching transaction trace plus block hash history, prestate, and block info
[block14.zip](https://github.com/privacy-scaling-explorations/zkevm-circuits/files/9659044/block14.zip)

**Comment by han0110** [comment] 2022-09-28 04:54
@AronisAt79 Checked again with [block14.zip](https://github.com/privacy-scaling-explorations/zkevm-circuits/files/9659044/block14.zip) and Tx circuit still passing.

I believe the lookup failure is caused by different randomness used in Keccak circuit, which should be fixed by #806. Could you run again the same block with latest `main` and see if errors have become less?

**Comment by AronisAt79** [comment] 2022-09-28 05:50
Thank you Han!

@leolara @pinkiebell would you please update circuits' revision dependency for zkevm-chain?

**Comment by pinkiebell** [comment] 2022-09-28 09:00
@han0110 I'm curious, any idea why the [simple keccak test](https://github.com/pinkiebell/tmp) passed before the randomness fix?

**Comment by han0110** [comment] 2022-09-28 09:22
Ah so current main is passing [simple keccak test](https://github.com/pinkiebell/tmp), after restarting chain with current main it can prove some block until the 14-th one? Is this understanding correct?

If so, I have no idea why it was passing the simple keccak test.. Let me dig into more to see.

**Comment by han0110** [comment] 2022-09-28 09:33
Hey @pinkiebell, I just realized there is more stuff to be updated in Keccak circuit for Super circuit (it's getting weirder why it was passing), please let me submit another patch and then let's decide if it's ready to start another test (repeatedly restart the chain seems annoying).

**Comment by AronisAt79** [comment] 2022-09-28 10:05
> Ah so current main is passing [simple keccak test](https://github.com/pinkiebell/tmp), after restarting chain with current main it can prove some block until the 14-th one [block14.zip](https://github.com/privacy-scaling-explorations/zkevm-circuits/files/9659044/block14.zip)? Is this understanding correct?
> 
> If so, I have no idea why it was passing the simple keccak test.. Let me dig into more to see.

@han0110 not exactly; when the chain is deployed, we configure the coordinator with dummy_proof=true. Therefore no proof request is sent to the prover service unless it is explicitly invoked. Usually the first blocks contain env setup Txs, ie fund deposits to l2, contract deployments and so on, which are blocks we only want to retest in regression. In this specific case, we only sent proof_request for block 14, which i believe contains a Tx optimized for max h/g ratio, with SDIVs (bench test for evm circuit). But i think it would also fail for block 1,2 and so on, as well, regardless of what's in the block.

**Comment by han0110** [comment] 2022-09-28 10:27
@AronisAt79 I see now, thanks for explaining all the details!

**Comment by aguzmant103** [comment] 2022-09-29 11:36
Possible approach:
- Focus on fixing possible issues in the Super Circuit to make sure it works as expected.
- Restart the chain again and see if it works.

**Comment by pinkiebell** [comment] 2022-10-05 14:15
Some new witness errors after to latest zkevm-circuits,
snippet:
```
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup Stack lookup (stored expression)". rw: Stack { rw_counter: 24, is_write: true, call_id: 1, stack_pointer: 1023, value: 128 }, rw index: (Stack, 0), 0th rw of step PUSH
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup CallContext lookup (stored expression)". rw: CallContext { rw_counter: 1, is_write: true, call_id: 1, field_tag: TxId, value: 1 }, rw index: (CallContext, 0), 0th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup CallContext lookup (stored expression)". rw: CallContext { rw_counter: 2, is_write: true, call_id: 1, field_tag: RwCounterEndOfReversion, value: 0 }, rw index: (CallContext, 1), 1th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup CallContext lookup (stored expression)". rw: CallContext { rw_counter: 3, is_write: true, call_id: 1, field_tag: IsPersistent, value: 1 }, rw index: (CallContext, 2), 2th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup CallContext lookup (stored expression)". rw: CallContext { rw_counter: 4, is_write: true, call_id: 1, field_tag: IsSuccess, value: 1 }, rw index: (CallContext, 3), 3th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup Account write (stored expression)". rw: Account { rw_counter: 5, is_write: true, account_address: 0xdf08f82de32b8d460adbe8d72043e3a7e25a3b39, field_tag: Nonce, value: 75, value_prev: 74 }, rw index: (Account, 0), 4th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup TxAccessListAccount write (stored expression)". rw: TxAccessListAccount { rw_counter: 6, is_write: true, tx_id: 1, account_address: 0xdf08f82de32b8d460adbe8d72043e3a7e25a3b39, is_warm: true, is_warm_prev: false }, rw index: (TxAccessListAccount, 0), 5th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup TxAccessListAccount write (stored expression)". rw: TxAccessListAccount { rw_counter: 7, is_write: true, tx_id: 1, account_address: 0x0000000000000000000000000000000000010000, is_warm: true, is_warm_prev: false }, rw index: (TxAccessListAccount, 1), 6th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup Account write (stored expression)". rw: Account { rw_counter: 8, is_write: true, account_address: 0xdf08f82de32b8d460adbe8d72043e3a7e25a3b39, field_tag: Balance, value: 99911051999999992, value_prev: 99999999999999992 }, rw index: (Account, 1), 7th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup Account write (stored expression)". rw: Account { rw_counter: 9, is_write: true, account_address: 0x0000000000000000000000000000000000010000, field_tag: Balance, value: 115792089237316195423570985008687907853269984665640564039457484007913129639910, value_prev: 115792089237316195423570985008687907853269984665640564039457484007913129639910 }, rw index: (Account, 2), 8th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup Account read (stored expression)". rw: Account { rw_counter: 10, is_write: false, account_address: 0x0000000000000000000000000000000000010000, field_tag: CodeHash, value: 106064417264452617865746442646238588754163462963496134417730329479324690365372, value_prev: 106064417264452617865746442646238588754163462963496134417730329479324690365372 }, rw index: (Account, 3), 9th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup CallContext lookup (stored expression)". rw: CallContext { rw_counter: 11, is_write: true, call_id: 1, field_tag: Depth, value: 1 }, rw index: (CallContext, 4), 10th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup CallContext lookup (stored expression)". rw: CallContext { rw_counter: 12, is_write: true, call_id: 1, field_tag: CallerAddress, value: 1273304967316882936049701685105397241436140354361 }, rw index: (CallContext, 5), 11th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup CallContext lookup (stored expression)". rw: CallContext { rw_counter: 13, is_write: true, call_id: 1, field_tag: CalleeAddress, value: 65536 }, rw index: (CallContext, 6), 12th rw of step BeginTx
[2022-10-05T13:59:01Z ERROR zkevm_circuits::evm_circuit::execution] incorrect rw witness. lookup input name: "rw lookup CallContext lookup (stored expression)". rw: CallContext { rw_counter: 14, is_write: true, call_id: 1, field_tag: CallDataOffset, value: 0 }, rw index: (CallContext, 7), 13th rw of step BeginTx
...
```

Full log + block fixtures can be found [here](https://github.com/pinkiebell/tmp/tree/master/36)

**Comment by pinkiebell** [comment] 2022-10-06 14:54
There is now a github workflow that executes the chain tests with the prover and uploads failures into a new branch. For example: https://github.com/privacy-scaling-explorations/zkevm-chain/commit/e01e60ec08c9bc71cb7a1e43271459330c184cd9
This one is also a rw witness related error. I hope that it makes future testing easier 🙏

**Comment by aguzmant103** [comment] 2022-10-27 11:34
@han0110 is working on this. Needs to confirm with @pinkiebell that this is not a blocker for https://github.com/privacy-scaling-explorations/zkevm-chain/issues/18

**Comment by pinkiebell** [comment] 2022-10-27 13:50
> @han0110 is working on this. Needs to confirm with @pinkiebell that this is not a blocker for [privacy-scaling-explorations/zkevm-chain#18](https://github.com/privacy-scaling-explorations/zkevm-chain/issues/18)

I will upgrade zkevm-circuits and run the SuperCircuit test again 👌 
Right now, we have support for the halo2 verifier for the PI circuit. So this issue only bocks the integration of the super circuit

**Comment by pinkiebell** [comment] 2022-10-28 04:31
The witness related errors are gone and new stuff popped up 🙂 
[complete log and fixtures](https://github.com/privacy-scaling-explorations/zkevm-chain/tree/prover-error-7423f8ad5b8c60984fb0892a78b53eaf53a43562/errors)
<details>

```
MockProver: Err(
    [
        ConstraintNotSatisfied {
            constraint: Constraint {
                gate: Gate {
                    index: 2575,
                    name: "squeeze",
                },
                index: 4,
                name: "hash rlc check",
            },
            location: InRegion {
                region: Region {
                    index: 23,
                    name: "assign keccak rows",
                },
                offset: 125,
            },
            cell_values: [
                (
                    VirtualCell {
                        name: "",
                        column: Column {
                            column_type: Advice,
                            index: 41,
                        },
                        rotation: 0,
                    },
                    "1",
                ),
                (
                    VirtualCell {
                        name: "",
                        column: Column {
                            column_type: Advice {
                                phase: Phase(
                                    1,
                                ),
                            },
                            index: 44,
                        },
                        rotation: 0,
                    },
                    "0x199ff30315265649b00cb40dbd49aecdc275aa2af42bef7b30f5a14f3a077cbd",
                ),
                (
                    VirtualCell {
                        name: "",
                        column: Column {
                            column_type: Fixed,
                            index: 2,
                        },
                        rotation: 0,
                    },
                    "0",
                ),
                (
                    VirtualCell {
                        name: "",
                        column: Column {
                            column_type: Fixed,
                            index: 5,
                        },
                        rotation: 0,
                    },
                    "1",
                ),
            ],
....
```

**Comment by han0110** [comment] 2022-11-02 06:58
> The witness related errors are gone and new stuff popped up 🙂
[complete log and fixtures](https://github.com/privacy-scaling-explorations/zkevm-chain/tree/prover-error-7423f8ad5b8c60984fb0892a78b53eaf53a43562/errors)

@pinkiebell PR #872 should make this block provable, tho I couldn't reproduce the keccak errors shown in the log.

**Comment by aguzmant103** [comment] 2022-11-10 12:44
Next steps: after PR is review, need to merge, need to run the integration tests and check if this issue can be closed.

**Comment by AronisAt79** [comment] 2022-11-12 10:09
Hello @Han, @pinkiebell,

i am running a simple l1>l2 deposit Tx and proof generation for the submitted block with following options:

```
{
     circuit: "pi",
     block: 1,
     rpc: "http://leader-testnet-geth:8545/",
     retry: false,
     param: "/testnet/",
     mock: false,
     aggregate: false,
     mock_feedback: true,
 }
```
is now successful.
On the other hand, with circuit:"super", proof fails with:

```
[2022-11-12T09:45:02Z WARN  zkevm_circuits::evm_circuit::execution::dummy] DummyGadget: wrong number of rw indices for ExecStep { call_index: 0, rw_indices: [(TxAccessListAccount, 2)], execution_state: DELEGATECALL, rw_counter: 867, program_counter: 45, stack_pointer: 1013, gas_left: 18987, gas_cost: 18731, memory_size: 768, reversible_write_counter: 3, log_id: 0, opcode: Some(DELEGATECALL) }
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', /usr/local/cargo/git/checkouts/zkevm-circuits-64f296067375034d/93abf02/zkevm-circuits/src/witness/rw.rs:306:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2022-11-12T09:45:03Z INFO  prover::shared_state] task_result: Err(
        "internal error: entered unreachable code",
    )
```

I understand the proof failure for circuit:super is known issue right? 


Also, when 'aggregate' is set to true (with circuit:pi), proof fails with `Err` value: NotEnoughRowsAvailable { current_k: 20 }". Coordinator stops sending proofRequests for subsequently submitted blocks
I will create a new issue for this one in case we need to track separately

**Comment by pinkiebell** [comment] 2022-11-12 11:37
Excerpt for the latest prover failure:
```
  name: "BeginTx",
  name: "Execution step",
  name: "assign keccak rows",
  name: "evm_word_rlc",
  name: "keccak_input_rlc",
  name: "length and data rlc",
  name: "signature address verify",
  name: "squeeze",
  name: "hash rlc check",
  name: "intermediate data rlc",
  name: "update data rlc",
  name: "value ⋅ (1 - value ⋅ value_inv)",
  name: "Rw",
  name: "Tx",
```

Branch: [prover-error-super-50316653b44b17ea3430258d8877197d9a3467dd](https://github.com/privacy-scaling-explorations/zkevm-chain/tree/prover-error-super-50316653b44b17ea3430258d8877197d9a3467dd)
zkevm-circuits: https://github.com/privacy-scaling-explorations/zkevm-circuits/commit/32166f6a4536107479f9c8bd37d7864f06e7debf

**Comment by AronisAt79** [comment] 2022-11-16 09:29
Hello @ChihChengLiang @han0110 @ed255 @pinkiebell ,

adding here proof test results for EVM & STATE worst case blocks. 

```
zkevm-chain commit   	: b739d5057d56485da4c5164bf88ed20ed324df43
zkevm-circuits = { git = "https://github.com/pinkiebell/zkevm-circuits.git", rev = "6bc581922807485cd9e89b4308fc08d679e5b6c2" }
```

**Comment by aguzmant103** [comment] 2022-11-24 12:11
@pinkiebell there was a proposal in the scrum meeting to close this task and reopen a new one for the latest error so the description is a bit cleaner of where we are. Are you ok with that? 
@han0110  is ok either way

**Closed** 2022-11-24 13:53 UTC
