### ISSUE TITLE
Keccak lookup error causes real prover to panic in testnet

### ISSUE THREAD

**Issue by AronisAt79** [privacy-scaling-explorations/zkevm-circuits#723] opened 2022-08-29 15:02 UTC
During proof generation (block consisting of a single deposit Tx):

[2022-08-29T12:52:09Z INFO  prover::shared_state] ProvingKey: generated and cached key=/testnet/21.bin944750200000596662096896
[2022-08-29T14:05:32Z INFO  prover::shared_state] task_result: Err(
        "The constraint system is not satisfied",
    )

commit: 2887314434c1fe52e88a7176385c2db09fadae8d

**Comment by AronisAt79** [comment] 2022-08-31 13:39
> That was fast!! Thanks @pinkiebell @AronisAt79 !!
> 
> Did we go for the approach discussed in our call @AronisAt79 ??

@CPerezz pretty much. But simpler :). No extra service//container created. Once a proof_request fails, mockProver is activated on the same container. @pinkiebell said that  we could also implement a proof_request option to control whether a real or mock prover is engaged per proof_request. I think that would be an awesome debug tool to consider.

**Comment by ChihChengLiang** [comment] 2022-09-12 10:00
@AronisAt79 @CPerezz @pinkiebell do we know what's the pre-state for the block?

**Comment by AronisAt79** [comment] 2022-09-12 11:24
> @AronisAt79 @CPerezz @pinkiebell do we know what's the pre-state for the block?

Hi @ChihChengLiang. Unfortunately not. I will need to repeat the test since the environment has been redeployed. How do i collect the block pre_state info?

**Comment by ChihChengLiang** [comment] 2022-09-12 14:12
I have no idea currently. Maybe @pinkiebell has some info. I can look into the prover code.

**Comment by pinkiebell** [comment] 2022-09-12 15:27
The `prestateTracer` 
```
{"id":0, "jsonrpc":"2.0","method":"debug_traceBlockByNumber", "params":["0x1", {"tracer":"prestateTracer"}]}
```
Returns for example:
```
{"jsonrpc":"2.0","id":0,"result":[{"result":{"0xdf08f82de32b8d460adbe8d72043e3a7e25a3b39":{"balance":"0x16345785d8a0000","nonce":0,"code":"0x","storage":{}}}}]}
```

**Comment by CPerezz** [comment] 2022-09-12 17:54
I think this should do @ChihChengLiang right? Since the failure is inside the `MSTORE` checks, this should allow to debug the entire thing. Specially since we already know the randomness.

**Comment by AronisAt79** [comment] 2022-09-12 21:44
thanks @pinkiebell! 
@ChihChengLiang i am attaching debug trace for block4 with  prestate tracer enabled, plus debug traces for block4 transactions.
[Block4_preStateTrace.zip](https://github.com/privacy-scaling-explorations/zkevm-circuits/files/9552007/Block4_preStateTrace.zip)
Mockprover log turned out huge, in case it is needed please let me know

**Comment by ChihChengLiang** [comment] 2022-09-16 13:54
Thank you @AronisAt79 for the prestate. Is there a chance we can get the block info? It would have the content of the block header and the transactions inside it.

**Comment by pinkiebell** [comment] 2022-09-17 06:38
@ChihChengLiang I looked your PR. I think the error must have something todo with not having the proper block/tx setup. So the data of the block is needed and (easier) to reproduce anyway.

I think it's best to pull-in a script that:
i) get the block data w/ full transactions
ii) fetches all history hashes
Iii) fetches prestate for the block in question

**Comment by pinkiebell** [comment] 2022-09-17 07:52
I added a helper script: https://github.com/privacy-scaling-explorations/zkevm-chain/commit/0dc460a454e90167084e96c676206b48d8c7debb

@AronisAt79 You have to retry this again. Sorry for the inconvenience 🙏

**Comment by AronisAt79** [comment] 2022-09-18 21:38
Hello,

@pinkiebell thanks for the script. I will add a debug option into our test tool to fetch that info. Can you please explain why you go back specifically 255 blocks in history? 

[block27.zip](https://github.com/privacy-scaling-explorations/zkevm-circuits/files/9595272/block27.zip)

@ChihChengLiang i am attaching fresh set of info plus tx traces. Will you need the prover log as well?

**Comment by ChihChengLiang** [comment] 2022-09-19 11:03
@AronisAt79 thanks for the data. Yeah prover log might help if it's not too much trouble for you.

**Comment by ChihChengLiang** [comment] 2022-09-20 05:39
@pinkiebell the bug seems to be fixed on main. Can you try the zkevm-main on zkevm-chain prover?

**Comment by pinkiebell** [comment] 2022-09-20 09:09
> @pinkiebell the bug seems to be fixed on main. Can you try the zkevm-main on zkevm-chain prover?

Will do.

**Comment by pinkiebell** [comment] 2022-09-20 10:38
@AronisAt79 Can we do a run with https://github.com/privacy-scaling-explorations/zkevm-chain/commit/d01a5c0b2816fd27c062903a9accfea328c07974 and see if it goes trough without errors?

**Comment by AronisAt79** [comment] 2022-09-20 10:47
> @AronisAt79 Can we do a run with [privacy-scaling-explorations/zkevm-chain@d01a5c0](https://github.com/privacy-scaling-explorations/zkevm-chain/commit/d01a5c0b2816fd27c062903a9accfea328c07974) and see if it goes trough without errors?

sure! on it

**Comment by ChihChengLiang** [comment] 2022-09-22 08:15
Close in favor of #790

**Closed by ChihChengLiang** 2022-09-22 08:15 UTC
Labels: crate-zkevm-circuits, T-bug
